# -*- coding: utf-8 -*-
"""app_bootcamp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185P4d-8q82dQGAlZ0nLYrTkz9LlY8kbq
"""

"""
Session 4: Streamlit Dashboard Complete
Dashboard RUP 2025 - Production Ready

Fokus: Tabs, Charts, Filtering, Caching, Export, Deploy
Durasi: 120 menit
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt

# ========================================
# KONFIGURASI HALAMAN
# ========================================
st.set_page_config(
    page_title="Student Social Media & Mental Health Dashboard",
    page_icon="🎓",
    layout="wide"
)

# ========================================
# CSS KUSTOM
# ========================================
st.markdown("""
<style>
.main-header {
    font-size: 2.4rem;
    font-weight: bold;
    text-align: center;
    color: #2E86C1;
}
</style>
""", unsafe_allow_html=True)

# ========================================
# LOAD DATA with CACHING
# ========================================
@st.cache_data(ttl=3600)  # Cache for 1 hour
def load_data():
    """Load RUP data with caching"""
    project_root = Path.cwd()
    data_path = project_root / 'Students-Social-Media-Addiction'

    if not data_path.exists():
        st.error(f"Dataset not found at {data_path}")
        st.stop()

    df = pd.read_parquet(data_path)
    # Convert date column
    df['tgl_pengumuman_paket'] = pd.to_datetime(df['tgl_pengumuman_paket'])
    return df

# Load data with progress
with st.spinner('⏳ Loading data...'):
    df = load_data()

# ========================================
# KATEGORI USIA
# ========================================
def age_group(age):
    if age < 18:
        return "<18"
    elif age <= 22:
        return "18–22"
    elif age <= 26:
        return "23–26"
    return "27+"

df["Age_Group"] = df["Age"].apply(age_group)

# ========================================
# KATEGORI KECANDUAN
# ========================================
def addiction_level(score):
    if score <= 3:
        return "Rendah"
    elif score <= 6:
        return "Sedang"
    return "Tinggi"

df["Addiction_Level"] = df["Addicted_Score"].apply(addiction_level)

# ========================================
# HEADER
# ========================================
st.markdown('<div class="main-header">🎓 Student Social Media & Mental Health Dashboard</div>', unsafe_allow_html=True)
st.markdown("""
Analisis **pola kecanduan penggunaan media sosial** terhadap **indikator pribadi, akademik,
dan kehidupan sosial mahasiswa**, mendukung **SDG 3 & SDG 4**.
""")
st.markdown("---")

# ========================================
# SIDEBAR FILTER
# ========================================
st.sidebar.header("🔍 Filter Data")

gender = st.sidebar.multiselect(
    "Jenis Kelamin",
    df["Gender"].unique(),
    df["Gender"].unique()
)

academic = st.sidebar.multiselect(
    "Jenjang Akademik",
    df["Academic_Level"].unique(),
    df["Academic_Level"].unique()
)

platform = st.sidebar.multiselect(
    "Platform Media Sosial",
    df["Most_Used_Platform"].unique(),
    df["Most_Used_Platform"].unique()
)

addiction = st.sidebar.multiselect(
    "Tingkat Kecanduan",
    df["Addiction_Level"].unique(),
    df["Addiction_Level"].unique()
)

academic_impact = st.sidebar.multiselect(
    "Dampak Akademik",
    df["Affects_Academic_Performance"].unique(),
    df["Affects_Academic_Performance"].unique()
)

usage_range = st.sidebar.slider(
    "Durasi Penggunaan Harian (Jam)",
    float(df["Avg_Daily_Usage_Hours"].min()),
    float(df["Avg_Daily_Usage_Hours"].max()),
    (
        float(df["Avg_Daily_Usage_Hours"].min()),
        float(df["Avg_Daily_Usage_Hours"].max())
    )
)

# ========================================
# FILTER DATA
# ========================================
filtered_df = df[
    (df["Gender"].isin(gender)) &
    (df["Academic_Level"].isin(academic)) &
    (df["Most_Used_Platform"].isin(platform)) &
    (df["Addiction_Level"].isin(addiction)) &
    (df["Affects_Academic_Performance"].isin(academic_impact)) &
    (df["Avg_Daily_Usage_Hours"].between(usage_range[0], usage_range[1]))
]

if filtered_df.empty:
    st.warning("⚠️ Tidak ada data sesuai filter")
    st.stop()

# ========================================
# KPI
# ========================================
st.header("📊 Ringkasan Statistik")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Jumlah Mahasiswa", len(filtered_df))
c2.metric("Rata-rata Jam Harian", round(filtered_df["Avg_Daily_Usage_Hours"].mean(), 2))
c3.metric("Skor Mental", round(filtered_df["Mental_Health_Score"].mean(), 2))
c4.metric("Skor Kecanduan", round(filtered_df["Addicted_Score"].mean(), 2))

st.markdown("---")

# ========================================
# TAB
# ========================================
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📱 Platform",
    "🧠 Indikator Pribadi",
    "🎓 Indikator Akademik",
    "👥 Kehidupan Sosial",
    "📋 Data"
])

# ========================================
# TAB 1 – PLATFORM
# ========================================
with tab1:
    fig = px.pie(
        filtered_df,
        names="Most_Used_Platform",
        hole=0.4,
        title="Distribusi Platform Media Sosial"
    )
    st.plotly_chart(fig, use_container_width=True)

# ========================================
# TAB 2 – INDIKATOR PRIBADI
# ========================================
with tab2:
    st.subheader("Kecanduan vs Kesehatan Mental")
    fig = px.box(
        filtered_df,
        x="Addiction_Level",
        y="Mental_Health_Score",
        color="Addiction_Level",
        title="Pola Kecanduan terhadap Kesehatan Mental"
    )
    st.plotly_chart(fig, use_container_width=True)

    st.subheader("Kecanduan vs Jam Tidur")
    fig = px.box(
        filtered_df,
        x="Addiction_Level",
        y="Sleep_Hours_Per_Night",
        color="Addiction_Level",
        title="Pola Kecanduan terhadap Jam Tidur"
    )
    st.plotly_chart(fig, use_container_width=True)

# ========================================
# TAB 3 – INDIKATOR AKADEMIK
# ========================================
with tab3:
    academic_pattern = (
        filtered_df
        .groupby(["Addiction_Level", "Affects_Academic_Performance"])
        .size()
        .reset_index(name="Jumlah")
    )

    fig = px.bar(
        academic_pattern,
        x="Addiction_Level",
        y="Jumlah",
        color="Affects_Academic_Performance",
        barmode="group",
        title="Pola Kecanduan terhadap Dampak Akademik"
    )
    st.plotly_chart(fig, use_container_width=True)

# ========================================
# TAB 4 – KEHIDUPAN SOSIAL
# ========================================
with tab4:
    fig = px.bar(
        filtered_df,
        x="Addiction_Level",
        color="Conflicts_Over_Social_Media",
        title="Kecanduan Media Sosial vs Konflik Kehidupan Sosial"
    )
    st.plotly_chart(fig, use_container_width=True)

    st.info("""
    📌 **Ringkasan Pola Kecanduan**
    - Kecanduan tinggi → jam tidur lebih rendah
    - Skor kesehatan mental menurun seiring kecanduan
    - Dampak akademik negatif meningkat
    - Konflik sosial lebih sering terjadi
    """)

# ========================================
# TAB 5 – DATA
# ========================================
with tab5:
    st.dataframe(filtered_df, use_container_width=True)

    csv = filtered_df.to_csv(index=False).encode("utf-8")
    st.download_button(
        "⬇️ Unduh Data Terfilter",
        csv,
        "student_filtered.csv",
        "text/csv"
    )

# ========================================
# FOOTER
# ========================================
st.markdown("---")
st.markdown("<center>📘 Dashboard Media Sosial & Kesehatan Mental Mahasiswa</center>", unsafe_allow_html=True)

